### ISSUE TITLE
Notification icon is hidden when a new notification occurs

### ISSUE THREAD

**Issue by Chamrosh** [nx-desktop/nx-plasma-look-and-feel#39]
I use the nx-desktop theme in OpenSuse
The problem is that when a new notification arrives, the notification icon is hidden and not displayed !!

![Screenshot_20200831_204631](https://user-images.githubusercontent.com/10561726/91742320-5a0e5a80-ebcb-11ea-82b1-b4d1262f13a1.png)
![Screenshot_20200831_204538](https://user-images.githubusercontent.com/10561726/91742327-5da1e180-ebcb-11ea-9c6b-f81ba1a1c29f.png)

**Comment by UriHerrera** [comment]
I don't see that happening with our system tray, so I'd assume that you're not using our system tray but the default in Plasma?.
