### ISSUE TITLE
Night Color Icon does not appear

### ISSUE THREAD

**Issue by Sarcasmo220** [nx-desktop/nx-plasma-look-and-feel#42]
**Describe the bug**
In the system tray applet, the icon for Night Color does not appear either when active or inactive.

**To Reproduce**
1. View inactive icons
2. Observe Night Color icon is not present

OR

1. Set time for Night Color to be active.
2. When time arrives, observe blank space on system tray where Night Color icon should be.

**Expected behavior**
Night Color icon should be present when both active or inactive on system tray.

**Desktop (please complete the following information):**
 - OS: Nitrux OS
 - Version 1.3.7

**Comment by UriHerrera** [comment]
Fixed in https://github.com/Nitrux/luv-icon-theme/commit/f11b67d153f1ed762a434f11b82e37ba0733aebc
