### ISSUE TITLE
Feature Request: Use NX Logo on Login screen

### ISSUE THREAD

**Issue by Sarcasmo220** [nx-desktop/nx-plasma-look-and-feel#43]
***Request***
Replace the logo of a generic person outline with the NX logo

***Explanation***
I tested out replacing the logo found in the sddm files for Nitrux theme with the one found on the Nitrux website, and I think it looks pretty good! It blends in with the modern-minimalism of the login screen better. Check out the screenshot below.

**Screenshots**
![preview](https://user-images.githubusercontent.com/68247163/109618050-f5857700-7aeb-11eb-8524-2af0669b0e8d.jpg)

**Comment by Sarcasmo220** [comment]
I thought I would also mess around with using the NXOS logo to see how that would look:
![nxos-logo](https://user-images.githubusercontent.com/68247163/109625203-e4d8ff00-7af3-11eb-8c25-3fc678525c34.png)

**Comment by UriHerrera** [comment]
In general, I'd like to improve the appearance of the SDDM theme. I welcome your suggestions.
