### ISSUE TITLE
Sddm login window not output to external monitor

### ISSUE THREAD

**Issue by nealbrophy** [nx-desktop/nx-plasma-look-and-feel#46]
**Describe the bug**
SDDM login window outputs to laptop screen even when laptop lid is shut and displays have been configured to output to external monitor only.

**To Reproduce**
1. Output display to external monitor (via HDMI in my case)
2. Set output to "External only" so no output on laptop screen
3. Shut laptop lid and logout/reboot
4. Login window not visible on external monitor

**Expected behavior**
Login window should appear on all screens or the active/primary screen only.

**Desktop (please complete the following information):**
 - OS: Nitrux 
 - Version 2.0.0

**Potential fix**
Comparing nitrux/nitrux-dark's 'Main.qml' to a different SDDM theme where the login window appeared on the external monitor I found that nitrux & nitrux-dark have the line `visible: primaryScreen` (line number 93 in both qmls). Commenting out this line resolved the issue with no side-effects (so far).
![image](https://user-images.githubusercontent.com/44747070/153623723-664eba96-e1d4-4cf9-b65e-d53dda158786.png)

**Comment by UriHerrera** [comment]
Fixed in https://github.com/nx-desktop/nx-plasma-look-and-feel/commit/6ca7c47103f413eb83244f2c618e3e38d9deea76
