### ISSUE TITLE
Is there support for NX Desktop Manager in NixOS?

### ISSUE THREAD

**Issue by Spencerx** [nx-desktop/nx-plasma-look-and-feel#47]
Just did a very general search on NixOS homepage to find package for NX Desktop Manager on NixOS?
I'm expecting to see support for @NixOS with it's 80000 strong package NixPkgs repository to see NX Desktop Manager here https://search.nixos.org/packages?query=NX+Desktop
  to see some support for NixOS, depends on the machine in use on the day switching from NixOS to NXOS should be seamless for a debian user or vice versa.

There's @BedrockLinux,  @blend-os, @Vanilla-OS which offer different routes to solve a specific problem for a specific user but they're all new and will have a level of complexity that scares most users away unless they don't mind getting to know what alpha testing is. I'm for it but for everyday use running NX & NixOS are enough with WayDroid in the background, anyone else can join in on their own route and see how this works out.

**Comment by UriHerrera** [comment]
I'm unsure what you're asking; what is _"NX Desktop Manager"_? 

Also, I believe you're confusing a lot of stuff. This repository is for the Look and Feel package; this issue isn't about that, it seems. Additionally, you're mixing Nix, NixOS, and Nitrux?

If you want to start a new public discussion, you can do it at our GitHub organization: https://github.com/Nitrux/nitrux-bug-tracker/discussions/new.
